# Pour tout push dans le repo
# - déclencher le build d'une nouvelle image docker en utilisant le Dockerfile
# - et faire un push vers dockerHub
name: build and push image
run-name: $(( github.actor )) is learning Github Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkhout@v3
    - run: tree
