name: Create and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch: # Permet de déclencher manuellement le workflow

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v3.3.0
        with:
          username: "d3lta29"
          password: "dckr_pat_sxOdBPlT4q_YmWOo0JUvBfyYuyc" # Assurez-vous que ce secret est défini dans vos paramètres GitHub

      - name: Build Docker image
        run: |
          docker build -t d3lta29/poire .

      - name: Push Docker image to Docker Hub
        run: |
          docker push d3lta29/poire
