name: Create Dockerfile

on:
  push:
    branches:
      - main
  workflow_dispatch: # Permet de déclencher manuellement le workflow

jobs:
  create_dockerfile: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Dockerfile #Créer et ecrit dans le fichier DockerFile les lignes "echo" suivantes :
        run: |
          echo "FROM node:20-alpine" > Dockerfile
          echo "WORKDIR /greg" >> Dockerfile
          echo "COPY . ." >> Dockerfile
          echo "RUN yarn install" >> Dockerfile
          echo 'CMD ["node", "src/index.js"]' >> Dockerfile
          echo "EXPOSE 3000" >> Dockerfile

      - name: Commit Dockerfile #Envoi le fichier Dockerfile sur la branche main utilisateur
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add Dockerfile
          git commit -m "Add Dockerfile created by GitHub Action"
          git push
