name: Create and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch: # Permet de déclencher manuellement le workflow

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        env:
          DOCKER_HUB_USERNAME: d3lta29
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}  # Définissez ce secret dans vos paramètres GitHub
        run: |
          echo $DOCKER_HUB_TOKEN | docker login -u $DOCKER_HUB_USERNAME --password-stdin

      - name: Build Docker image
        run: |
          docker build -t d3lta29/poire .

      - name: Push Docker image to Docker Hub
        run: |
          docker push d3lta29/poire
